spring.application.name=webshop-order-service
server.port=${PORT:9999}
product-service.base-url=${PRODUCT_SERVICE_BASE_URL:http://localhost:8081}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVER_URL:http://localhost:8080}/auth/jwks
server.forward-headers-strategy=framework
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_USERNAME}
spring.rabbitmq.port=${RABBITMQ_PORT:5671}
spring.rabbitmq.ssl.enabled=true